hal/core

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetricPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSourceStoreImpl.java
master: https://issues.jboss.org/browse/HAL-560
2.5.x: https://issues.jboss.org/browse/HAL-557
PRs:
master: https://github.com/hal/core/pull/23
2.5.x: https://github.com/hal/core/pull/25
> HAL-557 use :flush-idle-connection-in-pool

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetricPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSourceStoreImpl.java
master: https://issues.jboss.org/browse/HAL-560
2.5.x: https://issues.jboss.org/browse/HAL-557
PRs:
master: https://github.com/hal/core/pull/23
2.5.x: https://github.com/hal/core/pull/25
> HAL-560 use :flush-gracefully-connection-in-pool

- gui/src/main/java/org/jboss/as/console/client/shared/deployment/DeploymentTreeModel.java
> BZ1201685: Deployments name shortened in admin console.

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSource.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/XADataSource.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/wizard/NewXADatasourceWizard.java
JIRA: https://issues.jboss.org/browse/HAL-667
An attempt to fix wrong default attribute values handling.
> HAL-667 Add data-source adds certain attributes to non-default zero values

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXExecutionView.java
It should be externalized anyway.
> HAL-635: Runtime/Transaction typo fix.

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/PoolConfig.java
- gui/src/main/java/org/jboss/as/console/client/widgets/forms/EntityAdapter.java
- gui/src/main/java/org/jboss/as/console/client/widgets/tables/DataProviderFilter.java
Here is a simple fix - let me know what you think about it !
> BZ1220747:  Admin console is not behaving properly after applying deployment filter

- gui/src/main/java/org/jboss/as/console/client/domain/profiles/CloneProfileWizard.java
https://issues.jboss.org/browse/HAL-749
> HAL-749 - allow white space in profile names

- gui/src/main/java/org/jboss/as/console/client/rbac/internal/RunAsRoleTool.java
... even when user clicks Cancel
> [HAL-763] Run as Role dialog: web console is reloaded

- gui/src/main/java/org/jboss/as/console/client/shared/jvm/CreateJvmCmd.java
Fix a typo made in previous change in https://github.com/hal/core/pull/50
issue https://issues.jboss.org/browse/HAL-774
> [HAL-774] fix typo in previous change

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/forms/ClusterConnectionForm.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/model/ActivemqClusterConnection.java
https://issues.jboss.org/browse/HAL-827
https://issues.jboss.org/browse/JBEAP-990
> [HAL-827] Can not create messaging clustering connection

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/infinispan/v3/CachesPresenter.java
https://issues.jboss.org/browse/HAL-716
https://issues.jboss.org/browse/JBEAP-361
> [HAL-716] Can't change cache store attributes back to false from true

- dmr/src/main/java/org/jboss/dmr/client/IEEE754.java
- dmr/src/main/java/org/jboss/dmr/client/dispatch/impl/DMRHandler.java
https://issues.jboss.org/browse/JBEAP-359
https://issues.jboss.org/browse/HAL-822
> [HAL-822] Can't change cache attributes

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/forms/ClusterConnectionForm.java
https://issues.jboss.org/browse/HAL-828
https://issues.jboss.org/browse/JBEAP-992
Reasoning: I added setRequired(false) to all fields that have nillable=true in resource description.
> [HAL-828] Can not set cluster connection attributes to null

- gui/src/main/java/org/jboss/as/console/client/StringUtils.java
- gui/src/main/java/org/jboss/as/console/client/core/Header.java
- gui/src/main/java/org/jboss/as/console/client/domain/hosts/HostServerTable.java
- gui/src/main/java/org/jboss/as/console/client/search/IndexSuggestOracle.java
- gui/src/main/java/org/jboss/as/console/client/widgets/popups/ComboPicker.java
- gui/src/main/java/org/jboss/as/console/client/widgets/tables/ShortcutColumn.java
- gui/src/main/java/org/jboss/as/console/client/widgets/tabs/Tab.java
A simple cherry-pick from the [PR79](https://github.com/hal/core/pull/79) for the maintenance branch - !
> Code cleaning - reworking handle to emphasis (...) to centralize code to ease maintenance and limit potential side effect

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/MsgConnectionsPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/model/ActivemqBridge.java
https://issues.jboss.org/browse/HAL-903
https://issues.jboss.org/browse/JBEAP-1453
> [HAL-903] Cannot add discovery group to bridge attributes

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/forms/DefaultBridgeForm.java
https://issues.jboss.org/browse/JBEAP-1316
https://issues.jboss.org/browse/HAL-880
Changing validation of mandatory fields from "at least one" to "exactly one".
> [HAL-880] Problem with creating bridge in messaging subsystem

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/tx/TransactionView.java
Validate that the datasource name is provided when enabling JDBC
transaction log store.
> [HAL-942, JBEAP-1714] Validate changing transaction log store

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetrics.java
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1243175
JIRA: https://issues.jboss.org/browse/HAL-856
Upstream PR: https://github.com/hal/core/pull/74
> [HAL-856] fix for runtime DS view

- gui/src/main/java/org/jboss/as/console/client/v3/deployment/Templates.java
- gui/src/main/java/org/jboss/as/console/public/lab.css
https://issues.jboss.org/browse/JBEAP-978
https://issues.jboss.org/browse/HAL-823
* added scrollbar to deployment preview
> HAL-823, JBEAP-978 - In deployment preview just the limited number of groups the deployment is assigned to is displayed

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/tx/TransactionView.java
https://issues.jboss.org/browse/HAL-887
https://issues.jboss.org/browse/JBEAP-1357
Heiko previously rejected HAL-887, but this would fix incorrect error message ("Please set either UUID or socket binding" when user fills socket-max-ports without filling socket-bindings).
> HAL-887, JBEAP-1357: process-id-socket-max-ports setting inconsistency in web console configuration

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/infinispan/v3/CommonCacheAttributes.java
https://issues.jboss.org/browse/HAL-910
https://issues.jboss.org/browse/JBEAP-1504
> [HAL-910/JBEAP-1504] Resource focus change after edit is confusing

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSourceTemplates.java
https://issues.jboss.org/browse/HAL-1053
> [HAL-1053] minor update default user and passwrod to 'sa' in H2 datasource to facilitate testing.

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/AcceptorList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/ConnectorServiceList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/NewAcceptorWizard.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/NewConnectorServiceWizard.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/forms/AcceptorForm.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/forms/ConnectorServiceForm.java
https://issues.jboss.org/browse/JBEAP-3001
> [JBEAP-3001] Missing resource description in "Need Help?" box

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/remoting/ui/ConnectionEditor.java
fix https://issues.jboss.org/browse/HAL-1021
> HAL-1021 - Remote outbound connection wrong label

- gui/src/main/java/org/jboss/as/console/client/core/ReadRequiredResources.java
fix for https://issues.jboss.org/browse/HAL-1051
> HAL-1051 - r-r-d operation is missing locale attribute

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ResourceAdapterFinder.java
- gui/src/main/java/org/jboss/as/console/client/v3/widgets/AddResourceDialog.java
fix for https://issues.jboss.org/browse/HAL-1050
> HAL-1050 - Insufficient handling of new resource adapters

- gui/src/main/java/org/jboss/as/console/client/shared/general/SocketBindingPresenter.java
Additional refreshStore for clone and remove operations.
> HAL-1019 - Server group creation socket binding options not refreshed

- gui/src/main/java/org/jboss/as/console/client/widgets/nav/v3/ColumnFilter.java
https://issues.jboss.org/browse/JBEAP-3607 - port of #139 for 2.8.x branch
Replaced isFilterActive with currentFilterExpression != null since both values should change together. Reset the filterActive state when the ColumnFilter.clear() is called
> JBEAP-3607 Disable filtering before changing column's data

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSourceTemplates.java
https://issues.jboss.org/browse/JBEAP-2839
upstream HAL issue : https://issues.jboss.org/browse/HAL-1053
upstream master branch PR : https://github.com/hal/core/pull/142
> [JBEAP-2839] minor update default user and passwrod to 'sa' in H2 datasource to facilitate testing.

- gui/src/main/java/org/jboss/as/console/client/shared/general/SocketList.java
https://issues.jboss.org/browse/HAL-980
> HAL-980 - Can't change interface and fixed-port options on socket binding

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/security/v3/SecDomainPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/security/v3/SecDomainView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/security/v3/SecModule.java
https://issues.jboss.org/browse/HAL-979
> HAL-979 - New Login Module Code suggest-box not working properly

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/MsgDestinationsPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/QueueList.java
https://issues.jboss.org/browse/HAL-1024
> HAL-1024 - Cannot edit JMS queues

- gui/src/main/java/org/jboss/as/console/client/domain/groups/ServerGroupView.java
- gui/src/main/java/org/jboss/as/console/client/domain/hosts/ServerConfigView.java
- gui/src/main/java/org/jboss/as/console/client/domain/hosts/general/HostPropertiesView.java
- gui/src/main/java/org/jboss/as/console/client/shared/properties/PropertyEditor.java
https://issues.jboss.org/browse/HAL-761
> HAL-761 - Display boot-time value for server system property

- gui/src/main/webapp/less/main.less
2.8.x branch PR
master PR already merged: https://github.com/hal/core/pull/160/
upstream jira: https://issues.jboss.org/browse/HAL-1057
product jira: https://issues.jboss.org/browse/JBEAP-2553
> HAL-1057: make console centered in IE 11

- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
cherry-pick fix https://issues.jboss.org/browse/HAL-1048 for 2.8.x branch
requirement from new found https://issues.jboss.org/browse/JBEAP-3846
> fix for HAL-1048

- gui/src/main/java/org/jboss/as/console/client/tools/PageHeader.java
- gui/src/main/java/org/jboss/as/console/public/lab.css
JIRA: https://issues.jboss.org/browse/HAL-1068
> HAL-1068: allow large page header to wrap

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/modcluster/ModclusterView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/modcluster/model/Modcluster.java
https://issues.jboss.org/browse/HAL-1007
> HAL-1007 - ModCluster subsystem configuration missing "Connector" attribute

- gui/src/main/java/org/jboss/as/console/rebind/ProductConfigGenerator.java
Master PR: https://github.com/hal/core/pull/174
Issue: https://issues.jboss.org/browse/JBEAP-3923
> JBEAP-3923: HAL version fix. Maintanance branch.

- gui/src/main/java/org/jboss/as/console/rebind/ProductConfigGenerator.java
2.8.x branch PR: https://github.com/hal/core/pull/173
Issue: https://issues.jboss.org/browse/JBEAP-3923
> JBEAP-3923: HAL version fix. Master branch.

- gui/src/main/java/org/jboss/as/console/client/core/UIConstants.java
- gui/src/main/java/org/jboss/as/console/client/core/UIConstants.properties
- gui/src/main/java/org/jboss/as/console/client/shared/patching/PatchManager.java
- gui/src/main/java/org/jboss/as/console/client/shared/patching/ui/PatchInfoTable.java
JIRA: https://issues.jboss.org/browse/HAL-1069
2.9.x: https://github.com/hal/core/pull/192
2.8.x: https://github.com/hal/core/pull/191
> [HAL-1069] 2.8.x - use patch streams in patching view

- gui/src/main/java/org/jboss/as/console/client/widgets/nav/v3/ColumnFilter.java
Fixing issue introduced in 99feec0b0a79956a50ab44886cee18395a0c1671
Port of #179 for 2.8.x branch
JIRA: https://issues.jboss.org/browse/JBEAP-3607
> JBEAP-3607 Clearing filter resets column results

- gui/src/main/java/org/jboss/as/console/client/tools/PageHeader.java
- gui/src/main/java/org/jboss/as/console/public/lab.css
Issue: https://issues.jboss.org/browse/JBEAP-3898
Upstream issue: https://issues.jboss.org/browse/HAL-1068
Upstream PR #182
> JBEAP-3839: allow large page header to wrap

- gui/src/main/java/org/jboss/as/console/client/core/NameTokens.java
- gui/src/main/java/org/jboss/as/console/client/core/gin/CoreUI.java
- gui/src/main/java/org/jboss/as/console/client/core/gin/CoreUIModule.java
- gui/src/main/java/org/jboss/as/console/client/preview/PreviewContent.java
- gui/src/main/java/org/jboss/as/console/client/preview/content/undertow_filters.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/undertow_filters_de.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/undertow_filters_es.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/undertow_filters_fr.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/undertow_filters_ja.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/undertow_filters_ko.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/undertow_filters_pt-BR.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/undertow_filters_zh-Hans.html
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterRefEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FiltersView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/HostView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/HttpPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/HttpView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/UndertowFinderView.java
- gui/src/main/java/org/jboss/as/console/client/v3/dmr/ResourceDescription.java
https://issues.jboss.org/browse/HAL-779
- also contains a fix to ResourceDescription.hasAttributes()
> HAL-779 - Please add option to enable/disable the Undertow X-Powered-By.

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/naming/JndiPresenter.java
https://issues.jboss.org/browse/HAL-1028
> HAL-1028 - No message shown on JNDI view fails

- gui/src/main/java/org/jboss/as/console/client/standalone/runtime/StandaloneRuntimePresenter.java
JIRA: https://issues.jboss.org/browse/HAL-1077
> HAL-1077 Changed error when reloading server to a warning

- gui/src/main/java/org/jboss/as/console/client/standalone/runtime/StandaloneRuntimePresenter.java
JIRA: https://issues.jboss.org/browse/JBEAP-1382
2.8.x branch port of #197
> JBEAP-1382 Changed error when reloading server to a warning

- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinder.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinderView.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/wizard/AssignContentDialog.java
https://issues.jboss.org/browse/JBEAP-4236
Upstream PR: https://github.com/hal/core/pull/199
> [JBEAP-4236] Deployment preview info doesn't change when disabled

- gui/src/main/webapp/less/main.less
https://issues.jboss.org/browse/JBEAP-4535
> JBEAP-4535 Messages and user elements aren't vertically aligned

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/cluster/MsgClusteringPresenter.java
https://issues.jboss.org/browse/JBEAP-4588
upstream master branch PR: https://github.com/hal/core/pull/215
> [JBEAP-4588] Broadcast should allow to add optional field if there is another required field other than Name.

- gui/src/main/java/org/jboss/as/console/client/shared/homepage/GuidedTourHelper.java
JIRA: https://issues.jboss.org/browse/HAL-970
JBEAP: https://issues.jboss.org/browse/JBEAP-1949
> [HAL-970, JBEAP-1949] EAP tour window doesnt respect window sizes

- build/pom.xml
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceDetails.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/XADataSourceDetails.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSource.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/XADataSource.java
- gui/src/main/webapp/less/main.less
https://issues.jboss.org/browse/HAL-955
> HAL-955 - Can the data source attribute "spy" be added to the console

- build/pom.xml
- gui/src/main/webapp/less/main.less
https://issues.jboss.org/browse/HAL-792
* Also, increased the maximum heap for GWT SuperDevMode
> HAL-792 - Label is cut off

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSourceTemplates.java
https://issues.jboss.org/browse/HAL-1098
This is for EAP 7
> [HAL-1098] update url in template for MS SQLServer datasource.

- gui/src/main/java/org/jboss/as/console/client/domain/profiles/ColumnProfileView.java
- gui/src/main/java/org/jboss/as/console/client/domain/runtime/DomainRuntimeView.java
- gui/src/main/java/org/jboss/as/console/client/standalone/runtime/StandaloneRuntimeView.java
Issue: https://issues.jboss.org/browse/HAL-1074
> HAL-1074: clear preview after unselecting

- dmr/src/main/java/org/jboss/dmr/client/ModelDescriptionConstants.java
- gui/src/main/java/org/jboss/as/console/client/core/UIMessages.java
- gui/src/main/java/org/jboss/as/console/client/core/UIMessages.properties
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/JberetMetricsPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/Job.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/store/JberetStore.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/store/LoadJobsMetrics.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/store/RestartJob.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/store/StartJob.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/store/StopJob.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/ui/JberetMetricsView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/ui/JobsRuntimePanel.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/ui/ThreadPoolRuntimePanel.java
https://issues.jboss.org/browse/HAL-1104
> HAL-1104 - Batch Job Management and Monitoring GUI Support

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/charts/BulletGraphView.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/GeneralView.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXExecutionView.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXLogPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXLogView.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXMetricPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXMetricViewImpl.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXRollbackView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/ui/JobsRuntimePanel.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FiltersView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/HttpPresenter.java
https://issues.jboss.org/browse/HAL-1117
* Also, removed some unnecessary references of JUL
> HAL-1117 - Add monitoring attributes to the transaction subsystem

- dmr/src/main/java/org/jboss/dmr/client/ModelDescriptionConstants.java
- gui/src/main/java/org/jboss/as/console/client/core/NameTokens.java
- gui/src/main/java/org/jboss/as/console/client/core/gin/CoreUI.java
- gui/src/main/java/org/jboss/as/console/client/core/gin/CoreUIModule.java
- gui/src/main/java/org/jboss/as/console/client/preview/PreviewContent.java
- gui/src/main/java/org/jboss/as/console/client/preview/content/jms_bridge.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/jms_bridge_de.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/jms_bridge_es.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/jms_bridge_fr.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/jms_bridge_ja.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/jms_bridge_pt-BR.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/jms_bridge_zh-Hans.html
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ActivemqFinder.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ActivemqFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSBridgeList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSBridgePresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSBridgeSelectionAwareContext.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSBridgeView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/LoadActivemqServersCmd.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/MessagingAddress.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ProviderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/model/JmsBridge.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FiltersView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/UndertowFinderView.java
HAL-224 - JMS bridges not visible in bridges table
https://issues.jboss.org/browse/HAL-1093
https://issues.jboss.org/browse/HAL-224
> HAL-1093 - Allow adding JMS Bridge

- gui/src/main/java/org/jboss/as/console/client/shared/patching/PatchManager.java
7.0.z: https://issues.jboss.org/browse/JBEAP-4051
PR upstream: https://github.com/hal/core/pull/239
* re-apply JBEAP-4051 ([HAL-1069] caused a regression)
> [JBEAP-4051] Patch Management doesn't show the "Latest Applied Patch" correctly

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ThreadPoolEditor.java
Issue: https://issues.jboss.org/browse/HAL-1136
> [HAL-1136] Typo: "long-runnig" threads

- gui/src/main/webapp/less/main.less
Issue: https://issues.jboss.org/browse/HAL-1132
> HAL-1132: specify button font

- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeForm.java
https://issues.jboss.org/browse/JBEAP-4763
https://issues.jboss.org/browse/HAL-1112
> [JBEAP-4763 / HAL-1112] Web console is not able to read property attributes

- gui/src/main/java/org/jboss/as/console/client/core/UIMessages.properties
- gui/src/main/java/org/jboss/as/console/client/core/bootstrap/cors/BootstrapServerDialog.java
- gui/src/main/java/org/jboss/as/console/client/preview/paths.html
- gui/src/main/java/org/jboss/as/console/client/preview/paths_de.html
- gui/src/main/java/org/jboss/as/console/client/preview/paths_es.html
- gui/src/main/java/org/jboss/as/console/client/preview/paths_fr.html
- gui/src/main/java/org/jboss/as/console/client/preview/paths_ja.html
- gui/src/main/java/org/jboss/as/console/client/preview/paths_pt-BR.html
- gui/src/main/java/org/jboss/as/console/client/preview/paths_zh-Hans.html
* HAL-1015 - Contribute page improvement
Enlarged a bit the width of dialog to make room for the additional height.
> * HAL-982 - Paths section description contains escaped quotes in domain mode

- gui/src/main/webapp/less/main.less
Issue: https://issues.jboss.org/browse/JBEAP-5002
Upstream issue: https://issues.jboss.org/browse/HAL-1132
Upstream PR: #249
> JBEAP-5002: specify button font

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ActivemqFinder.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/LoadActivemqServersCmd.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/MessagingAddress.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ProviderView.java
Issue: https://issues.jboss.org/browse/JBEAP-4956
Upstream issue: https://issues.jboss.org/browse/HAL-1137
Upstream PR: #261
> JBEAP-4956: messaging - enable directory path configuration

- gui/src/main/java/org/jboss/as/console/client/administration/accesscontrol/ui/AccessControlView.java
- gui/src/main/java/org/jboss/as/console/client/domain/hosts/ColumnHostView.java
- gui/src/main/java/org/jboss/as/console/client/domain/profiles/ColumnProfileView.java
- gui/src/main/java/org/jboss/as/console/client/domain/runtime/DomainRuntimeView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/infinispan/v3/CacheFinder.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ResourceAdapterFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/mail/MailFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/messaging/HornetqFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/picketlink/PicketLinkFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/security/v3/SecDomainFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/UndertowFinderView.java
- gui/src/main/java/org/jboss/as/console/client/standalone/ColumnServerView.java
- gui/src/main/java/org/jboss/as/console/client/standalone/runtime/StandaloneRuntimeView.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinderView.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/StandaloneDeploymentFinderView.java
Issue: https://issues.jboss.org/browse/HAL-1144
> HAL-1144: use ScrollPanel for previews

- gui/src/main/java/org/jboss/as/console/client/widgets/nav/v3/FinderColumn.java
Issue: https://issues.jboss.org/browse/HAL-1146
> HAL-1146: fix scrollable column height

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/store/JberetStore.java
https://issues.jboss.org/browse/HAL-1160
> HAL-1160 - Cannot list batch jobs in runtime view for domain mode

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/logger/MasterDetailTemplate.java
Issue: https://issues.jboss.org/browse/HAL-1159
> HAL-1159: fix property reselection

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/wizard/DataSourceNameItem.java
https://issues.jboss.org/browse/HAL-902
master: https://github.com/hal/core/pull/289
2.8.x: https://github.com/hal/core/pull/288
> [HAL-902] Allow white space in DS name

- gui/src/main/java/org/jboss/as/console/client/administration/accesscontrol/ui/AccessControlView.java
- gui/src/main/java/org/jboss/as/console/client/domain/hosts/ColumnHostView.java
- gui/src/main/java/org/jboss/as/console/client/domain/profiles/ColumnProfileView.java
- gui/src/main/java/org/jboss/as/console/client/domain/runtime/DomainRuntimeView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/infinispan/v3/CacheFinder.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ResourceAdapterFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/mail/MailFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/messaging/HornetqFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/picketlink/PicketLinkFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/security/v3/SecDomainFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/UndertowFinderView.java
- gui/src/main/java/org/jboss/as/console/client/standalone/ColumnServerView.java
- gui/src/main/java/org/jboss/as/console/client/standalone/runtime/StandaloneRuntimeView.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinderView.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/StandaloneDeploymentFinderView.java
Issue: https://issues.jboss.org/browse/JBEAP-5266
Upstream issue: https://issues.jboss.org/browse/HAL-1144
Upstream PR: #270
> JBEAP-5266: use ScrollPanel for previews

- gui/src/main/java/org/jboss/as/console/client/tools/ChildView.java
- gui/src/main/java/org/jboss/as/console/client/tools/ModelBrowserView.java
- gui/src/main/java/org/jboss/as/console/client/tools/PageHeader.java
Issue: https://issues.jboss.org/browse/JBEAP-5367
Upstream issue: https://issues.jboss.org/browse/HAL-1149
Upstream PR: #279
> JBEAP-5367: decode URL segments

- gui/src/main/java/org/jboss/as/console/client/widgets/nav/v3/FinderColumn.java
Issue: https://issues.jboss.org/browse/JBEAP-5369
Upstream issue: https://issues.jboss.org/browse/HAL-1146
Upstream PR: #277
> JBEAP-5369: fix scrollable column height

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/modcluster/ModclusterView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/modcluster/model/Modcluster.java
Issue: https://issues.jboss.org/browse/HAL-1150
> HAL-1150, JBEAP-5763: expose proxies in ModCluster settings

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/Job.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/store/JberetStore.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/ui/JobsRuntimePanel.java
https://issues.jboss.org/browse/HAL-1161
> HAL-1161 - Not possible to start batch job using web console if job id is not same as job XML file name

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/StackOverview.java
https://issues.jboss.org/browse/HAL-1170
https://issues.jboss.org/browse/JBEAP-5022
> [HAL-1170] Add textual indication of what protocol stack is being removed

- gui/src/main/java/org/jboss/as/console/client/tools/ModelBrowserView.java
Issue: https://issues.jboss.org/browse/HAL-1180
> HAL-1180, JBEAP-4953: do not use placeholder in singleton items

- gui/src/main/java/org/jboss/as/console/client/core/NameTokens.java
- gui/src/main/java/org/jboss/as/console/client/core/gin/CoreUI.java
- gui/src/main/java/org/jboss/as/console/client/core/gin/CoreUIModule.java
- gui/src/main/java/org/jboss/as/console/client/preview/content/messaging_provider.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/messaging_provider_de.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/messaging_provider_es.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/messaging_provider_fr.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/messaging_provider_ja.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/messaging_provider_pt-BR.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/messaging_provider_zh-Hans.html
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ActivemqFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/PreparedTransactionsPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/PreparedTransactionsView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/model/PreparedTransaction.java
Issue: https://issues.jboss.org/browse/HAL-1177
> HAL-1177, JBEAP-4563: implement transaction management for Artemis

- gui/src/main/java/org/jboss/as/console/client/shared/hosts/ConfigurationChangesEditor.java
HAL-1183 - There is no separator between resource addresses in configuration changes monitoring
https://issues.jboss.org/browse/HAL-1183
HAL-1182 - Composite operation is not marked as composite in recent configuration changes
https://issues.jboss.org/browse/HAL-1182
> HAL-1183 / HAL-1182 - Fixes for Recent Configuration Changes

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSBridgeList.java
- gui/src/main/java/org/jboss/as/console/client/v3/widgets/PropertyEditor.java
https://issues.jboss.org/browse/HAL-1185
> HAL-1185 - Add and remove buttons for context properties are still vsible even when no JMS Bridge is selected

- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinder.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinderView.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/StandaloneDeploymentFinder.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/StandaloneDeploymentFinderView.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/wizard/ReplaceDeploymentWizard.java
name
master: https://issues.jboss.org/browse/HAL-972
2.8.x: https://issues.jboss.org/browse/HAL-1173
> HAL-972 - Replace deployment shouldn't allow to specify name and runtime

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/ui/JobsRuntimePanel.java
https://issues.jboss.org/browse/HAL-1191
JBEAP one: https://issues.jboss.org/browse/JBEAP-6174
> [HAL-1191] fix incorrect column name in Batch jobs status table.

- gui/src/main/java/org/jboss/as/console/client/tools/ChildView.java
- gui/src/main/java/org/jboss/as/console/client/tools/ModelBrowser.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
Issue: https://issues.jboss.org/browse/HAL-1184
> HAL-1184, JBEAP-4950: do not require name for singleton resources

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXMetricPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXRollbackView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/tx/model/TransactionManager.java
https://issues.jboss.org/browse/HAL-1192
> HAL-1192- System Failures in Transactions subsystem runtime view doesn't show number-of-system-rollbacks

- gui/src/main/java/org/jboss/as/console/client/shared/state/ReloadState.java
- gui/src/main/java/org/jboss/as/console/client/standalone/runtime/StandaloneRuntimePresenter.java
- gui/src/main/java/org/jboss/as/console/client/standalone/runtime/StandaloneRuntimeView.java
https://issues.jboss.org/browse/HAL-939
master: https://github.com/hal/core/pull/284
2.8.x: https://github.com/hal/core/pull/285
> [HAL-939] - add restart procedure for standalone

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/ConnectorMetricView.java
https://issues.jboss.org/browse/JBEAP-6331
This is EAP 7.1 issue, so I presume only master branch commit is needed.
> JBEAP-6331 - unneeded scrollbar on undertow metrics page

- gui/src/main/java/org/jboss/as/console/client/shared/help/HelpSystem.java
JBEAP: https://issues.jboss.org/browse/JBEAP-6351
JIRA: https://issues.jboss.org/browse/HAL-1200
> [JBEAP-6351] Help text paragraphs when adding group are swapped

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/security/v3/SecDomainPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/security/v3/SecDomainView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/security/v3/SecModule.java
Issue: https://issues.jboss.org/browse/JBEAP-5170
Upstream issue: https://issues.jboss.org/browse/HAL-979
Upstream PR: #158
> JBEAP-5170: provide suggestions for authentication modules

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/modcluster/ModclusterView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/modcluster/model/Modcluster.java
Issue: https://issues.jboss.org/browse/JBEAP-5190
Upstream issue: https://issues.jboss.org/browse/HAL-1150
Upstream PR: #293
> JBEAP-5190: expose proxies in ModCluster settings

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ThreadPoolEditor.java
Issue: https://issues.jboss.org/browse/HAL-1218
> HAL-1218, JBEAP-6720: make keepalive-time/time required

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/ServerList.java
See https://issues.jboss.org/browse/HAL-1221
> HAL-1221 Undertow runtime description clarification

- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
https://issues.jboss.org/browse/HAL-1215
No JBEAP so far, awaiting QA.
> [HAL-1215] - allow white spaces in name box from ModelNodeFormBuilder

- dmr/src/main/java/org/jboss/dmr/client/ModelDescriptionConstants.java
- gui/src/main/java/org/jboss/as/console/client/meta/Capabilities.java
- gui/src/main/java/org/jboss/as/console/client/meta/Capability.java
- gui/src/main/java/org/jboss/as/console/client/meta/CoreCapabilitiesRegister.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/modcluster/ModclusterView.java
https://issues.jboss.org/browse/HAL-1190
> HAL-1190 - Enhance CoreCapabilitiesRegister to load from /core-service=capability-registry

- gui/src/main/java/org/jboss/as/console/client/tools/ChildView.java
- gui/src/main/java/org/jboss/as/console/client/tools/FormView.java
- gui/src/main/java/org/jboss/as/console/client/tools/ModelBrowserValidators.java
Issue: [HAL-1199](https://issues.jboss.org/browse/HAL-1199)
> HAL-1199, JBEAP-6418: add custom validator for naming subsystem

- gui/src/main/java/org/jboss/as/console/client/core/Footer.java
Issue: https://issues.jboss.org/browse/JBEAP-4929
Upstream issue: https://issues.jboss.org/browse/HAL-1157
Upstream PR: #282
> JBEAP-4929: fix expression resolver launching

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/logger/MasterDetailTemplate.java
Issue: https://issues.jboss.org/browse/JBEAP-4991
Upstream issue: https://issues.jboss.org/browse/HAL-1159
Upstream PR: #286
> JBEAP-4991: fix property reselection

- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DeploymentBrowseContentPresenter.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DeploymentBrowseContentView.java
this enables the download operation, as read-operation is an allowed to run in HTTP GET mode.
https://issues.jboss.org/browse/HAL-1147
> HAL-1147- Support managed exploded deployments

- gui/src/main/java/org/jboss/as/console/client/shared/SubsystemMetaData.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/MsgConnectionsPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/MsgConnectionsView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/PooledConnectionFactoryView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/ElytronGenericResourceView.java
- gui/src/main/java/org/jboss/as/console/client/v3/behaviour/SelectionFilteringStatementContext.java
https://issues.jboss.org/browse/HAL-1231
- ElytronGenericResourceView: Removed a duplicate invocation of table.setSelectionModel(selectionModel);
> HAL-1231 - Add statistics for JMS pooled-connection-factory

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterPresenter.java
https://issues.jboss.org/browse/HAL-1234
> HAL-1234 - No error message appears when adding ModCluster filter in Undertow subsystem in Web Console

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/EJB3Presenter.java
https://issues.jboss.org/browse/HAL-1233
> HAL-1233 - Cannot create bean pool with defined max pool size in Web Console

- gui/src/main/java/org/jboss/as/console/client/shared/general/SocketGroupList.java
Changes made to backport issue [HAL-778] and bugzilla 1393746 raised.
> Changes for BZ_1393746

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/BeanPoolView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/EJB3Presenter.java
https://issues.jboss.org/browse/HAL-1243
> HAL-1243 - Not possible to create EJB 3 thread pool using web console

- gui/src/main/java/org/jboss/as/console/client/domain/runtime/DomainRuntimePresenter.java
JBEAP: https://issues.jboss.org/browse/JBEAP-7404
JIRA: https://issues.jboss.org/browse/HAL-1246
> [JBEAP-7404] Wrong dialog title when suspending server in managed domain

- gui/src/main/java/org/jboss/as/console/client/tools/ChildView.java
- gui/src/main/java/org/jboss/as/console/client/tools/FormView.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
https://issues.jboss.org/browse/HAL-1248
> HAL-1248 - Deprecated security related attributes are not visible in Web Console

- gui/src/main/java/org/jboss/as/console/client/shared/general/PathManagementPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/general/PathManagementView.java
- gui/src/main/java/org/jboss/as/console/client/shared/general/model/Path.java
https://issues.jboss.org/browse/HAL-1258
JBEAP-7767 - Better error visualization to user in Path screen
https://issues.jboss.org/browse/JBEAP-7767
> HAL-1258 - Enhancements to Path configuration in Web Console

- gui/src/main/java/org/jboss/as/console/client/v3/widgets/wizard/Wizard.java
https://issues.jboss.org/browse/HAL-1257
> HAL-1257 - Datasource remains saved in Web Console if user closes wizard after test connection is performed

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FiltersView.java
https://issues.jboss.org/browse/HAL-1235
> HAL-1235 - It is not possible to disable some checkboxes in Undertow filters in Web Console

- gui/src/main/java/org/jboss/as/console/client/tools/ModelBrowser.java
https://issues.jboss.org/browse/HAL-1154
> HAL-1154 - Web console always shows false as value of JMX subsystem's show-model attribute

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetrics.java
https://issues.jboss.org/browse/HAL-1260
> HAL-1260 - Add button to refresh the pool statistics for datasources

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/activemq/ActivemqMetricPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/activemq/PreparedTransactionManagement.java
https://issues.jboss.org/browse/HAL-1261
> HAL-1261 - Add button to refresh the prepared transactions statistics for messaging

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/StackStep1.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/StackStep2.java
https://issues.jboss.org/browse/HAL-1262
> HAL-1262 - add socket binding suggestion box to jgroups view

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXLogView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/FilterEditor.java
https://issues.jboss.org/browse/HAL-1066
* also a minor fix to the FilterEditor handling of selected filter.
> HAL-1066 - Remove button tries to remove a nonexistent transaction in screen Transaction Logs

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/MechanismProviderFilteringSaslServerFilterEditor.java
https://issues.jboss.org/browse/HAL-1264
> HAL-1264 - Show defaul value for version-comparison attribute in mechanism-provider-filtering-sasl-server-factory view

- gui/src/main/java/org/jboss/as/console/client/tools/ChildView.java
JBEAP: https://issues.jboss.org/browse/JBEAP-6811
JIRA: https://issues.jboss.org/browse/HAL-1268
> [JBEAP-6811] Resource removed from table remains selected

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/PropertiesRealmView.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ComplexAttributeForm.java
HAL: [HAL-1271](https://issues.jboss.org/browse/HAL-1271)
JBEAP: [JBEAP-8162](https://issues.jboss.org/browse/JBEAP-8162)
> HAL-1271: fix handling of groups-properties

- gui/src/main/java/org/jboss/as/console/client/core/UIConstants.properties
- gui/src/main/java/org/jboss/as/console/client/core/UIConstants_de.properties
- gui/src/main/java/org/jboss/as/console/client/core/UIConstants_es.properties
- gui/src/main/java/org/jboss/as/console/client/core/UIConstants_fr.properties
- gui/src/main/java/org/jboss/as/console/client/core/UIConstants_ja.properties
- gui/src/main/java/org/jboss/as/console/client/core/UIConstants_pt_BR.properties
- gui/src/main/java/org/jboss/as/console/client/core/UIConstants_zh_Hans.properties
- gui/src/main/java/org/jboss/as/console/client/shared/homepage/HomepageView.java
Issue: [JBEAP-6804](https://issues.jboss.org/browse/JBEAP-6804)
Upstream Issue: [HAL-1274](https://issues.jboss.org/browse/HAL-1274)
> JBEAP-6804 - Web console home page points to wrong quickstart page

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/GenericStoreView.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
https://issues.jboss.org/browse/HAL-1285
* Also, adds a validator for mutually exclusive fields in ModelNodeFormBuilder
> HAL-1285 - Not possible to create Elytron Credetial Store without all optional attributes of capability-reference specified

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceConnectionEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceFinder.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/wizard/NewDatasourceWizard.java
- gui/src/main/java/org/jboss/as/console/client/v3/widgets/wizard/Wizard.java
https://issues.jboss.org/browse/HAL-1284
* Also renamed the attribute from "ccm" to "use-ccm", as it is in the model.
> HAL-1284 - It is not possible to add new datasource in Web Console

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/ElytronGenericResourceView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/GenericStoreView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/SecurityDomainRealmEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/SecurityDomainView.java
https://issues.jboss.org/browse/HAL-1286
> HAL-1286 - Neither suggestion nor drop-down list for default realm is present when creating security domain

- gui/src/main/java/org/jboss/as/console/client/meta/CoreCapabilitiesRegister.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/ApplicationSecurityDomainView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/ContainerView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/EJB3Presenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/EJBView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/SubsystemView.java
https://issues.jboss.org/browse/JBEAP-8570
https://issues.jboss.org/browse/HAL-1291
The screenshot of the new "Application Security Domain" view is attached in the JBEAP issue.
> HAL-1291 elytron security domain configuration in EJB subsystem

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSBridgeList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ProviderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/BridgesList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/CredentialReferenceFormValidation.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/ElytronResourceWithCredentialReferenceView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/GenericStoreView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/XADataSourceEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSourceStoreImpl.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/mail/ServerConfigView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/ApplicationSecurityDomainResourceView.java
https://issues.jboss.org/browse/HAL-1296
> HAL-1296 - Validate credential-reference attribute value on client side in Web Console

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/CredentialReferenceFormValidation.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/store/ElytronStore.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/ElytronResourceWithCredentialReferenceView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/GenericStoreView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/ApplicationSecurityDomainResourceView.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ComplexAttributeForm.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
This adds the form validation for the add modal dialogs and fix the write-attribute on ElytronStore for the credential-reference.
> HAL-1296 Validate credential-reference attribute value on client side in Web Console

- gui/src/main/java/org/jboss/as/console/client/meta/CoreCapabilitiesRegister.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ActivemqFinder.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSBridgeList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ProviderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/BridgesList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/MsgConnectionsPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/CredentialReferenceAlternativesFormValidation.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ConnectionDefList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ResourceAdapterPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/XADataSourceEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSourceStoreImpl.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/mail/MailPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/mail/ServerConfigView.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ComplexAttributeForm.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
https://issues.jboss.org/browse/HAL-1300
> HAL-1300 - Add alternatives validator for credential-reference

- gui/src/main/java/org/jboss/as/console/client/v3/stores/domain/HostStore.java
- gui/src/main/java/org/jboss/as/console/client/v3/stores/domain/ServerStore.java
https://issues.jboss.org/browse/JBEAP-9147
https://issues.jboss.org/browse/HAL-1301
> HAL-1301 host is not set when browsing domain via server-groups

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/AddStackHelpPanel.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/StackStep1.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/StackStep2.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/help_step1.html
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/help_step2.html
https://issues.jboss.org/browse/HAL-1306
> HAL-1306/JBEAP-4944 - Help section of JGroups "add" dialog doesn't work

- gui/src/main/webapp/less/main.less
https://issues.jboss.org/browse/HAL-1313
> HAL-1313 - Bad style in subsystem configuration tab header

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/ConfigurableHttpServerMechanismFactoryFilterEditor.java
https://issues.jboss.org/browse/HAL-1315
> HAL-1315 - Mandatory 'enabling' checkbox when adding Elytron Configurable HTTP Server Mechanism filter does not work

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/mail/MailServerDefinition.java
https://issues.jboss.org/browse/HAL-1320
> HAL-1320 - tls attribute is not saved when form is saved

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/BridgesList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/MsgConnectionsPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/forms/DefaultBridgeForm.java
...when creating new bridge (causes server validation error)
* also couldn't edit static-connectors of existing bridge
https://issues.jboss.org/browse/HAL-1317
https://issues.jboss.org/browse/JBEAP-9614
> HAL-1317 attributes supplied with empty string instead of undefined

- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
https://issues.jboss.org/browse/HAL-1322
> HAL-1322 - Enables "alternatives" and "requires" validator by default for ModelNodeFormBuilder

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/SSLView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/TrustManagerView.java
https://issues.jboss.org/browse/HAL-1330
> HAL-1330 - Not possible to see and edit Elytron trust manager certificate-revocation-list

- gui/src/main/java/org/jboss/as/console/client/tools/DownloadUtil.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DeploymentBrowseContentPresenter.java
- gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinderView.java
https://issues.jboss.org/browse/HAL-1336
> HAL-1336 - Links to download deployment content download whole deployment instead of single files

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/TransformerView.java
HAL-1341 Not possible to create Elytron regex-validating-principal-transformer with match = false in web console
https://issues.jboss.org/browse/HAL-1342
https://issues.jboss.org/browse/HAL-1341
> HAL-1342 Not possible to create Elytron regex-principal-transformer in web console

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/BridgesList.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/store/ElytronStore.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/AuthenticationContextMatchRulesEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/IdentityAttributeMappingView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/JdbcRealmPrincipalsQueryView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/LdapRealmView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/NewIdentityAttributesView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/PropertiesRealmView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/XADataSourceEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/mail/ServerConfigView.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/ComplexAttributeForm.java
HAL-1344 - It is not possible to create LDAP security realm in Web Console
https://issues.jboss.org/browse/HAL-1344
HAL-1345 - It is not possible to remove LDAP security realm in Web Console
https://issues.jboss.org/browse/HAL-1345
HAL-1346 - No configuration change of a LDAP security realm's attribute is propagated to model
https://issues.jboss.org/browse/HAL-1346
HAL-1347 - Window won't close after clicking save when adding new Properties security realm in Web Console
https://issues.jboss.org/browse/HAL-1347
Also reverted PR #365 as it was not correct to set the nillable child attributes of a parent resource, because those child attributes must keep its constraints.
> Fix elytron issues

- gui/src/main/java/org/jboss/as/console/client/shared/hosts/ConfigurationChangesPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/mail/MailPresenter.java
HAL-1349 - It is not possible to change value of outbound-socket-binding-ref in mail server settings in Web Console
https://issues.jboss.org/browse/HAL-1349
HAL-1343 - Update configuration changes to use new subsystem
https://issues.jboss.org/browse/HAL-1343
> Fix for mail save and address of configuration changes

- gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
https://issues.jboss.org/browse/HAL-1351
> HAL-1351 - Datasource in Management model cannot be saved

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/AuthenticationContextMatchRulesEditor.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/mapper/SimplePermissionMappingEditor.java
HAL-1354 - Not possible to add permissions of permission-mappings of Elytron simple-permission-mapper
https://issues.jboss.org/browse/HAL-1354
HAL-1352 - It is not possible to match rule in authentication context configuration in Web Console
https://issues.jboss.org/browse/HAL-1352
> Fixes for Elytron configuration

- gui/src/main/java/org/jboss/as/console/client/domain/groups/deployment/ContentRepositoryPanel.java
This is backport of 551e6f415d20384416243b292511b7bc3fa1ee7a from 2.6 to 2.5 branch
https://issues.jboss.org/browse/HAL-633
https://bugzilla.redhat.com/show_bug.cgi?id=1208250
> HAL-633 Backport from 2.6 branch

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/ElytronGenericResourceView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/mapper/SimplePermissionMappingEditor.java
https://issues.jboss.org/browse/HAL-1353
> HAL-1353 - Not possible to view permissions of permission-mappings of Elytron simple-permission-mapper

- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_factory.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_factory_de.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_factory_es.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_factory_fr.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_factory_ja.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_factory_pt-BR.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_factory_zh-Hans.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_settings.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_settings_de.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_settings_es.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_settings_fr.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_settings_ja.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_settings_pt-BR.html
- gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_settings_za-Hans.html
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ElytronFactoryPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ElytronFinderView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ElytronPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/store/ElytronStore.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/ElytronView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/GenericListComplexAttribute.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/LogsView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/OthersView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/PolicyView.java
- gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/ElytronFactoryView.java
https://issues.jboss.org/browse/HAL-1360
* Also, moved "tranformers" from "Other" to "Factory" finder menu, as the pager limited the number of tabs to 4.
> HAL-1360 - Implement missing elytron resources

- gui/src/main/java/org/jboss/as/console/client/shared/subsys/logger/LoggerView.java
[https://issues.jboss.org/browse/HAL-1362]
[https://issues.jboss.org/browse/JBEAP-4967]
> [JBEAP-4967] Change tab names in Logging subsystem configuration

- gui/src/main/java/org/jboss/as/console/client/v3/stores/domain/HostStore.java
- gui/src/main/java/org/jboss/as/console/client/v3/stores/domain/ServerStore.java
Pull request for 7.0.x - cherry-pick from commit ID 3977743e0101f74f5a65a4d4ca2ab77b011e2b90
Jira 7.0.x : https://issues.jboss.org/browse/JBEAP-11749
7.1.x /hal 
https://issues.jboss.org/browse/JBEAP-9147
https://issues.jboss.org/browse/HAL-1301
https://github.com/hal/core/pull/387
> In Managed domain , accessing the ActiveMQ subsystem via the server group on management console gives an HTTP 500

- gui/src/main/java/org/jboss/as/console/client/v3/dmr/AddressTemplate.java
- gui/src/main/java/org/jboss/as/console/mbui/widgets/AddressUtils.java
- gui/src/test/java/org/jboss/as/console/client/v3/dmr/AddressTemplateTest.java
- gui/src/test/java/org/jboss/as/console/mbui/widgets/AddressUtilsTest.java
Issue: https://issues.jboss.org/browse/JBEAP-12087
> [JBEAP-12087] Details within "Subsystem: naming" not shown in web console

- gui/src/main/java/org/jboss/as/console/client/Console.java
- gui/src/main/java/org/jboss/as/console/client/core/bootstrap/hal/LoadMainApp.java
JBEAP: https://issues.jboss.org/browse/JBEAP-12870
upstream: https://issues.jboss.org/browse/WFLY-9289
upstream PR: https://github.com/hal/core/pull/444
> [JBEAP-12870] Name of domain is not reflected on the JBoss EAP tag

- gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetricPresenter.java
- gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetrics.java
https://issues.jboss.org/browse/HAL-1457
> [HAL-1457] read Data Source Metrics description under demand.
