hal/core

gui/src/main/java/org/jboss/as/console/client/domain/hosts/general/NewHostJvmWizard.java, gui/src/main/java/org/jboss/as/console/client/shared/jvm/CreateJvmCmd.java, gui/src/main/java/org/jboss/as/console/client/shared/jvm/JvmEditor.java
https://issues.jboss.org/browse/HAL-774 and https://bugzilla.redhat.com/show_bug.cgi?id=1248009
heapSize and maxHeapSize are nillable attributes, They should accept undefined values in console as CLI instance does.
"heap-size" => {
...
"nillable" => true,
...
},
"max-heap-size" => {
...
"nillable" => true,
...
},
=> [HAL-774] JVM attributes heapSize and maxHeapSize should be nillable.

gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetrics.java
Backporting [HAL-563: Add pager to datasource tables in #ds-metrics](https://github.com/hal/core/commit/3b82718227704218f2308d9701fa11d7344bf91d) to resolve issue on EAP 6.4.
=> Bz1251969 - When we create 10+ datasources in standalone.xml, then we cant see all the datasources in runtime tab

gui/src/main/java/org/jboss/as/console/client/domain/groups/deployment/ContentRepositoryPanel.java
BZ 6.4.z: https://bugzilla.redhat.com/show_bug.cgi?id=1256819
No upstream required
Clearing up the selection model during reset.
=> [BZ-1256819] Incorrect display of application name while assigning a new application to the ServerGroup.

gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeForm.java
ModelValue.asInt() was throwing IllegalArgumentException when value was was undefined.
I'm returning FormItem.VALUE_SEMANTICS.UNDEFINED, because that is what ModelNodeForm.getChangedValues() would use anyway at https://github.com/hal/core/blob/master/gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeForm.java#L389.
Also, the IllegalArgumentException is not caught anywhere and is not communicated to user, so it seems as if operation was successful, except the green confirmation panel is not displayed. Not sure where to fix that.
=> [HAL-764] Unable to unset wsdl-port and wsdl-secure-port via console

gui/src/main/java/org/jboss/as/console/client/domain/groups/deployment/AssignToGroupWizard.java
My previous commit did not really fixed the issue has expected. This one is (or at least should). 
No PR is needed for upstream.
=> BZ1201685: Deployments name shortened in admin console of Jboss EAP 6 (followup)

gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceConnectionEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/XADataSourceConnection.java
JIRA: https://issues.jboss.org/browse/HAL-856
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1243175
=> [HAL-856] DataSources - use test-connection-in-pool op for determining  verify button privilegues

gui/src/main/java/org/jboss/as/console/client/core/settings/SettingsPresenterWidget.java, gui/src/main/java/org/jboss/as/console/client/core/settings/SettingsView.java
Problem was that PopupViewImpl#showAndReposition() was called instead of #show(), so the overridden method in SettingsView was not invoked.
https://issues.jboss.org/browse/HAL-893
https://issues.jboss.org/browse/JBEAP-1377
=> [HAL-893] Impossible to disable usage data collection by web console.

gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetrics.java
JIRA: https://issues.jboss.org/browse/HAL-856
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1243175
=> [HAL-856] DataSources - use test-connection-in-pool op for determining verify button privilegues

gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/BeanPoolView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/CachesView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/EJB3Presenter.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/PassivationView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/RemotingProfileView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/ServiceViewTemplate.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/ejb3/ThreadPoolView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/infinispan/v3/CommonCacheAttributes.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/io/IOPanel.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/jberet/ui/MasterDetailPanel.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/JcaBootstrapEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ThreadPoolEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/logger/CategoryView.java, gui/src/main/java/org/jboss/as/console/client/standalone/deploymentscanner/DeploymentScannerView.java
https://issues.jboss.org/browse/HAL-910
https://issues.jboss.org/browse/JBEAP-1504
Fixed couple of views so that selection in a table doesn't reset to the first row after editing.
Most times I just removed ```selectionModel.clear()``` in ```update()``` methods and added ```SelectionChangeEvent.fire(selectionModel)``` which triggers ```form.edit(<updated instance>)```.
I was testing replacing ```dataProvider.setList()``` with ```dataProvider.getList().addAll()``` like:
```
protected void update(final List<Property> models) {
dataProvider.getList().clear();
dataProvider.getList().addAll(models);
table.selectDefaultEntity();
SelectionChangeEvent.fire(selectionModel);
}
```
which helped to prevent selection resetting, but then table.selectDefaultEntity() was still seeing old values, so I …
=> HAL-910, JBEAP-1504: Resource focus change after edit is confusing

gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/AJPListenerView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/AbstractListenerView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/HttpListenerView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/HttpsListenerView.java
pjelinek pointed another pages whetre table selection changes after edditing.
https://issues.jboss.org/browse/JBEAP-1504
https://issues.jboss.org/browse/HAL-910
PR is basically replacing
```java
public void setData(List<Property> data) {
selectionModel.clear();
dataProvider.setList(data);
table.selectDefaultEntity();
}
```
with
```java
public void setData(List<Property> data) {
dataProvider.setList(data);
if (data.isEmpty()) {
selectionModel.clear();
} else {
table.selectDefaultEntity();
}
}
```
Moreover three modified *ListenerViews are refactored to inherit from common ancestor to avoid code duplication, since they are practically identical.
=> [JBEAP-1504, HAL-910] table focus changes after editting

gui/src/main/java/org/jboss/as/console/client/shared/runtime/jms/JMSMetricPresenter.java
https://issues.jboss.org/browse/HAL-1017
Although there is no such same tab as attached screen capture (in JBEAP-2493 ) in this version
=> [HAL-1017] JMSMetricPresenter always uses "default" as part of operation address even if name is changed.

dmr/src/main/java/org/jboss/dmr/client/ModelDescriptionConstants.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/MsgConnectionsPresenter.java
https://issues.jboss.org/browse/HAL-903
When static-connectors is changed from previously non-empty to empty
value, operation step (undefine-attribute nor write-attibute) for this
field is not added to DMR.
=> [HAL-903, JBEAP-1453] Cannot add discovery group to bridge attributes

gui/src/main/java/org/jboss/as/console/client/shared/subsys/infinispan/v3/CommonCacheAttributes.java
https://issues.jboss.org/browse/JBEAP-1504
Upstream PR: https://github.com/hal/core/pull/126
Also checked that it doesn't break HAL-1012 again (Infinispan cache screens are not cleared when a resource is removed - https://issues.jboss.org/browse/HAL-1012)
=> [HAL-910/JBEAP-1504] Resource focus change after edit is confusing

bom/pom.xml
https://bugzilla.redhat.com/show_bug.cgi?id=1289495 upgrade ballroom to 2.1.10.Final for EAP 6
need CDW Acks on bugzilla. and release ballroom 2.1.10.Final first
=> BZ1289495 (Backport) Upgrade ballroom to 2.1.10.Final

gui/src/main/java/org/jboss/as/console/client/widgets/nav/v3/ColumnFilter.java
https://issues.jboss.org/browse/HAL-1052 - for master branch
Replaced isFilterActive with currentFilterExpression != null since both values should change together. Reset the filterActive state when the ColumnFilter.clear() is called
=> HAL-1052 Disable filtering before changing column's data

gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinder.java, gui/src/main/java/org/jboss/as/console/client/v3/deployment/DomainDeploymentFinderView.java, gui/src/main/java/org/jboss/as/console/client/v3/deployment/StandaloneDeploymentFinder.java, gui/src/main/java/org/jboss/as/console/client/v3/deployment/StandaloneDeploymentFinderView.java, gui/src/main/java/org/jboss/as/console/client/v3/deployment/wizard/ReplaceDeploymentWizard.java
https://issues.jboss.org/browse/HAL-972
In fact, the replace operation, preserve the actual deployment name and runtime-name
=> HAL-972 - Replace deployment shouldn't allow to specify name and runtime-name

gui/src/main/java/org/jboss/as/console/client/domain/hosts/HostMgmtPresenter.java, gui/src/main/java/org/jboss/as/console/client/domain/runtime/DomainRuntimePresenter.java, gui/src/main/java/org/jboss/as/console/client/domain/topology/ServerGroupOpV3.java, gui/src/main/java/org/jboss/as/console/client/shared/state/ReloadState.java
https://issues.jboss.org/browse/HAL-991
Also it contains a fix for the reload/restart/stop operation at group level for the case where some server is stopped, the stepResult for the server is disabled/stopped, so it should be considered.
=> HAL-991 - Domain mode only asks to reload configuration once

gui/src/main/java/org/jboss/as/console/client/widgets/nav/v3/ColumnFilter.java
Fixing issue introduced in 354531bebeeda5aceece474e1146031f121b6383
JIRA: https://issues.jboss.org/browse/HAL-1052
=> HAL-1052 Clearing filter resets column results

gui/src/main/java/org/jboss/as/console/client/shared/patching/PatchManager.java
Jira Upstream: https://issues.jboss.org/browse/HAL-1072
setting the proper host during patch info fetch operation.
=> [BZ-1319994] Patch Management doesn't show the "Latest Applied Patch" correctly

gui/src/main/java/org/jboss/as/console/client/shared/CoreBeanFactory.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/AggregatedJMSModel.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/CoreQueueEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/CoreQueueList.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSQueueList.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/JMSTopicList.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/LoadJMSCmd.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/MsgDestinationsPresenter.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/MsgDestinationsView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/NewCoreQueueWizard.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/NewJMSQueueWizard.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/MsgConnectionsPresenter.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/model/ActivemqCoreQueue.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/model/ActivemqJMSQueue.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/model/ActivemqJMSTopic.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/ResourceAdapterPresenter.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/jgroups/StackOverview.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/undertow/ConnectorMetrics.java, gui/src/main/java/org/jboss/as/console/client/tools/modelling/workbench/repository/UndertowExample.java
https://issues.jboss.org/browse/HAL-225
Also
* dos2unix: CoreBeanFactory
* renamed some variables and classes from Queue to JMSQueue, to differentiate between the core queue and jms queue.
=> HAL-225 - Core queues are not visible in destinations listing

gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/model/DataSourceTemplates.java
https://issues.jboss.org/browse/HAL-1098
=> [HAL-1098] update url in template for MS SQLServer datasource.

gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ActivemqFinder.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/LoadActivemqServersCmd.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/MessagingAddress.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/ProviderView.java
Issue: https://issues.jboss.org/browse/HAL-1137
=> HAL-1137: messaging - enable directory path configuration

gui/src/main/java/org/jboss/as/console/client/core/UIConstants.java, gui/src/main/java/org/jboss/as/console/client/core/UIConstants.properties, gui/src/main/java/org/jboss/as/console/client/shared/patching/PatchInfo.java, gui/src/main/java/org/jboss/as/console/client/shared/patching/PatchManager.java, gui/src/main/java/org/jboss/as/console/client/shared/patching/ui/PatchInfoTable.java
https://issues.jboss.org/browse/JBEAP-5004
https://issues.jboss.org/browse/HAL-1134
Adding "In effect?" column to PatchInfoTable to indicate if a patch was overwritten by newer cumulative patch.
=> [HAL-1134] One-off patches overridden by CPs should be marked as such

gui/src/main/java/org/jboss/as/console/client/v3/dmr/AddressTemplate.java, gui/src/main/java/org/jboss/as/console/mbui/widgets/AddressUtils.java, gui/src/test/java/org/jboss/as/console/client/v3/dmr/AddressTemplateTest.java, gui/src/test/java/org/jboss/as/console/mbui/widgets/AddressUtilsTest.java
https://issues.jboss.org/browse/JBEAP-5053
https://issues.jboss.org/browse/HAL-1127
Problem was that binding address was converted by `AddressUtils#toString()` to string "/subsystem=naming/binding=java:/global/a" and that was parsed by `AddressTemplate` to tokens
```
subsystem=naming
binding=java:
global
a
```
instead of
```
subsystem=naming
binding=java:/global/a
```
which lead to failure.
Fixed by:
* making `AddressUtils#toString(ModelNode address)` escape '/' characters in Property values,
* making `AddressTemplate.StringTokenizer` understand escaping.
=> [JBEAP-5053 / HAL-1127] naming binding cannot be removed

gui/src/main/java/org/jboss/as/console/client/domain/groups/ServerGroupView.java
EAP 6 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1352049
No upstream change required, already fixed in 2.8.x/master.
This is prerequisite for https://bugzilla.redhat.com/show_bug.cgi?id=1343591.
=> [BZ-1352049] Security context of propertyEditor in ServerGroupView is never changed

gui/src/main/java/org/jboss/as/console/client/shared/jvm/JvmEditor.java
https://issues.jboss.org/browse/HAL-1143
=> [HAL-1143] "JVM Options" should not be marked with asterisk

gui/src/main/java/org/jboss/as/console/client/tools/ChildView.java, gui/src/main/java/org/jboss/as/console/client/tools/ModelBrowserView.java, gui/src/main/java/org/jboss/as/console/client/tools/PageHeader.java
Issue: https://issues.jboss.org/browse/HAL-1149
=> HAL-1149: decode URL segments

gui/src/main/java/org/jboss/as/console/client/core/Footer.java
Issue: https://issues.jboss.org/browse/HAL-1157
----
Changed the menu to just fire an event like it's implemented in [InputElementWrapper].(https://github.com/hal/ballroom/blob/2.3.15/widgets/src/main/java/org/jboss/ballroom/client/widgets/forms/InputElementWrapper.java#L70-L76)
=> HAL-1157: fix expression resolver launching

gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/GeneralView.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/tx/TXRollbackView.java
https://issues.jboss.org/browse/HAL-1116
Also removed the attribute number-of-total-rollbacks because it is missing from DMR result.
=> HAL-1116 Expose stats for transaction System Rollbacks and Average Commit Time in the GUI

dmr/src/main/java/org/jboss/dmr/client/ModelDescriptionConstants.java, gui/src/main/java/org/jboss/as/console/client/core/ReadRequiredResources.java, gui/src/main/java/org/jboss/as/console/client/core/UIConstants.java, gui/src/main/java/org/jboss/as/console/client/core/UIConstants.properties, gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetricPresenter.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetricView.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/ds/DataSourceMetrics.java, gui/src/main/java/org/jboss/as/console/client/v3/behaviour/SelectionAwareContext.java, gui/src/main/java/org/jboss/as/console/client/v3/behaviour/SelectionFilteringStatementContext.java
https://issues.jboss.org/browse/HAL-1167
the runtime-only=storage check is performed only when the matchingAddress returns false this cover the corner case of r-r-d for /subsystem=datasources/data-source=*/statistics=pool because the fix of WFCORE-1737 resolves the datasource=* wildcard
SelectionFilteringStatementContext is the general SelectionFilteringAwareContext, can be reused. Not used now, but added for later use.
=> HAL-1167 - Display datasource runtime attributes

gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/files/LogFilePanel.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/files/LogFilesPresenter.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/files/LogFilesTable.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/files/LogFilesTabs.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/files/LogFilesView.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/files/StreamingProgress.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/store/LogStore.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/store/ReadLogFilesForRefresh.java, gui/src/main/java/org/jboss/as/console/client/shared/runtime/logging/store/RefreshLogFile.java
https://issues.jboss.org/browse/JBEAP-4963
https://issues.jboss.org/browse/HAL-1151
Downstream PR: https://github.com/hal/core/pull/314
Adds refresh buttons to log files table and log file panel.
=> JBEAP-4963, HAL-1151: Unable to refresh the log viewer page

gui/src/main/java/org/jboss/as/console/client/shared/runtime/ws/WebServiceRuntimeView.java
JIRA: https://issues.jboss.org/projects/HAL/issues/HAL-865
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1135137
=> [HAL-865] - Refresh button on webservices runtime view does not refreh statistics

gui/src/main/java/org/jboss/as/console/client/domain/runtime/DomainRuntimePresenter.java
Reverts hal/core#342. Merged this by accident into the 2.8.x branch
=> Revert "[JBEAP-7404] Wrong dialog title when suspending server in managed domain"

gui/src/main/java/org/jboss/as/console/client/meta/CoreCapabilitiesRegister.java, gui/src/main/java/org/jboss/as/console/client/v3/widgets/SuggestionResource.java, gui/src/main/java/org/jboss/as/console/mbui/widgets/AddressUtils.java
https://issues.jboss.org/browse/HAL-1255
Some small fix and enhancements:
* fix for ModelBrowser, when starts at ROOT node, use an empty string instead.
* fix to consider the org.wildfly.domain.profile capability
=> HAL-1255 - Configuration of singleton policy in singleton subsystem dissapears in Web Console

gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_security_realm.html, gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_security_realm_de.html, gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_security_realm_es.html, gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_security_realm_fr.html, gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_security_realm_ja.html, gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_security_realm_pt-BR.html, gui/src/main/java/org/jboss/as/console/client/preview/content/elytron_security_realm_za-Hans.html, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ElytronFinderView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ElytronSecurityRealmPresenter.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/store/ElytronStore.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/AuthenticationConfigurationView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/AuthenticationContextMatchRulesEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/AuthenticationContextView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/AuthenticationView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/ElytronSecurityRealmView.java
https://issues.jboss.org/browse/HAL-1259
=> HAL-1259 - Add elytron authentication-* resources to HAL

gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/wizard/DriverStep.java
Major and minor version fields aren't used for anything.
https://issues.jboss.org/browse/HAL-1293
https://issues.jboss.org/browse/JBEAP-8759
=> HAL-1293 Major and minor versions in datasource wizard are unnecessary

gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/CustomCredentialSecurityFactoryView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/FactoryView.java
https://issues.jboss.org/browse/HAL-1265
workaround to allow testing elytron subsystem in HAL, until it is fixed in the subsystem level.
=> HAL-1265 - Not possible to create Elytron custom credetial security factory in standalone mode

gui/src/main/java/org/jboss/as/console/client/shared/subsys/activemq/connections/BridgesList.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/SecurityDomainView.java, gui/src/main/java/org/jboss/as/console/mbui/widgets/ModelNodeFormBuilder.java
* HAL-1326 - Not possible to create security domain in Elytron subsystem configuration without outflow-security-domains attribute specified
* HAL-1325 - It is not possible to set -1 to reconnect attempts attribute of messaging bridge
https://issues.jboss.org/browse/HAL-1325
https://issues.jboss.org/browse/HAL-1326
=> HAL-1325 / HAL-1326 - two small fixes for ActiveMQ Bridge and Elytron security domain

gui/src/main/java/org/jboss/as/console/client/shared/hosts/ConfigurationChangesEditor.java
https://issues.jboss.org/browse/HAL-1355
=> HAL-1355 - Remote address in not shown in configuration changes table in Web Console

gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/AuthenticationContextMatchRulesEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/IdentityAttributeMappingView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/JdbcRealmPrincipalsQueryView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/LdapRealmView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/NewIdentityAttributesView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/ConfigurableHttpServerMechanismFactoryFilterEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/ConfigurableSaslServerFactoryFilterEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/GenericAuthenticationMechanismFactoryEditor.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/factory/MechanismProviderFilteringSaslServerFilterEditor.java
* HAL-1357 - Disable nested tables add/remove buttons if there are no table items
https://issues.jboss.org/browse/HAL-1357
=> Fix form submission of ldap-realm related to "search-recursive" attribute and disable tablebuttons

gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ElytronPresenter.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/store/ElytronStore.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/ElytronView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/LogsView.java, gui/src/main/java/org/jboss/as/console/client/shared/subsys/elytron/ui/SSLView.java
https://issues.jboss.org/browse/HAL-1363
=> HAL-1363 - Add new log elytron resources

gui/src/main/java/org/jboss/as/console/client/shared/subsys/jca/DataSourceConnectionEditor.java
Issue: https://issues.jboss.org/browse/HAL-1389
=> [HAL-1389] Datasource "Use CCM" value always reported as "false" in the web console
